version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  frontend:
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    env_file:
      - ./.env

  postgres:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    build: ../backend
    restart: always
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
      - ../backend:/code
      - ../infra/.env:/code/foodgram/.env
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - web

  grocery:
    container_name: grocery
    build: ../external_grocery_service
    ports:
      - "8080:8080"
    depends_on:
      - web
