# Generated by Django 2.2.28 on 2024-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=200, verbose_name='Роль пользователя'),
        ),
    ]
